#!/bin/bash
#
# Simply Lightning - A versatile shell utility that simplifies Bitcoin
# Lightning Network packages management while offering a suite of handy
# tools for seamless node operations.
#
# (c) 2025 0xeeLi - MIT License
#
sli_version="0.1.1"

# --- Configurable Variables ---

SLI_DIR="$HOME/.sli"
LIT_DIR="$HOME/.lit"
LIT_CONF="$LIT_DIR/lit.conf"
LND_DIR="$HOME/.lnd"
WALLET_PASS="$LND_DIR/wallet.pass"
EDITOR="nano"

# Load optional custom SLi config file
[ -f "$SLI_DIR/sli.conf" ] && source "$SLI_DIR/sli.conf"

# --- Global Variables ---

INSTALLED_PKGS=${SLI_DIR}/packages
CACHE_DIR=${SLI_DIR}/cache
PKGS_LIST=${SLI_DIR}/packages.list
PKGS_URL="https://raw.githubusercontent.com/0xeeli/sli/refs/heads/main/packages.list"

# SLi Wallet
SLIWA_LOG="${SLI_DIR/sliwa.log}"

# Colors
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
YELLOW='\033[0;33m'
RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m' # No color

#
# --- Helper Functions ---
#

# Display usage instructions (ident with space)
usage() {
	cat << EOT
Usage: $(basename $0) [command|tool] [pkg|arg] [arg]
$(print_separator)
$(echo -e "${YELLOW}Commands:${NC}")
  init               Initialize: sli lit wallet
  start              Start a deamon: litd
  stop               Stop a deamon: litd
  rs|restart         Restart a deamon: litd
  sc|show-config     Display config file: lit.conf
  ed|edit            Edit a config file: lit.conf
  lg|logs            Show last logs for a service (default: 30 lines)
  st|status          Show service status

$(echo -e "${YELLOW}Tools:${NC}")
  m2h|macaroon-hex   Get the HEX format of a macaroon
  gpw|gen-passwords  Gen new passwords for the wallet and Lit UI
  wa|wallet          Run 'sli wa' to display usage

$(echo -e "${YELLOW}Packages Manager:${NC}")
  in|install         Install a package
  up|upgrade         Upgrade installed packages
  ls|list            List installed and available packages
  cc|clean-cache     Remove downloaded packges tarball
  rm|remove          Remove a package
EOT
}

wallet_usage() {
	cat << EOT
Usage: $(basename $0) [wa|wallet] [command]
$(print_separator)
  new         Create a ₿TC onchain address
  lsaddr      List onchain wallet addresses
  send        Send ₿TC onchain
  openchan    Open a channel
EOT
}

print_separator() {
	echo -e "${PURPLE}--------------------------------------------------------------------------------${NC}"
}

# Check if a command is available
check_command() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo -e "Error: ${RED}$1${NC} is required but not installed."
		echo "" && exit 1
	fi
}

# Log events for SLi Wallet
log_action() { echo "$(date '+%Y-%m-%d %H:%M:%S') : $1" >> "$SLI_DIR/sliwa.log"; }

#
# --- Core Functions ---
#

# Should be run at first usage - Self install ;-)
sli_init() {
	pkg="sli"
	echo "⚡️ SLi Initialization"
	print_separator
	echo -e "Creating data structure in: ${YELLOW}$SLI_DIR${NC}"
	mkdir -p ${INSTALLED_PKGS}/${pkg} ${CACHE_DIR}
	echo -e "Storing curent SLi version: ${CYAN}$sli_version${NC}"
	echo "version=\"$sli_version\"" > ${INSTALLED_PKGS}/${pkg}/pkg.conf
	echo -e "Installing sli: /usr/local/bin/${pkg}"
	sudo cp -f ${0} /usr/local/bin
	echo "/usr/local/bin/sli" >  ${INSTALLED_PKGS}/${pkg}/files.list
	[ -f "$PKGS_LIST" ] || pkgs_get_list
	print_separator
}

# Used for upgrade, we keep main branch for now since we have control
# on packages.list to modify versions.
sli_install() {
	
	PKG_NAME="sli"
	SRC_URL="https://github.com/0xeeli/sli/archive/refs/heads"
	PKG_VERSION="$(pkg_get_version $PKG_NAME)"
	TARBALL="main.zip"
	SRC_DIR="sli-main"
	DL_URL=${SRC_URL}/${TARBALL}

	# Pre install
	pkg_pre_install "sli" "$PKG_VERSION"
	pkg_download_tarball
	pkg_extract_tarball

	# Install to /usr/local/bin
	echo -e "${CYAN}Install path: /usr/local/bin${NC}"
	echo " * Installing: sli"
	sudo cp -f ${SRC_DIR}/${PKG_NAME} /usr/local/bin
	echo "/usr/local/bin/sli" > ${PKG_DATA}/files.list
	
	# Post install
	pkg_post_install
}

# Let user use lit in place of litd
service_check() {
	if [ -z "$2" ]; then
		echo "Missing service name. Usage: sli $1 <service>"
		echo "" && exit 1
	fi
	if [ "$2" == "lit" ]; then
		service="litd"
	else
		service="$2"
	fi
}

service_start() {
	service_check "$@" || return 1
	if [ "$(systemctl is-active ${service})" != "active" ]; then
		echo "⚡️ Starting $service service..."
		sudo systemctl start ${service}
	else
		echo "⚡️ $service service is active."
	fi
	wallet_db_exist
}

service_stop() {
	service_check "$@" || return 1
	if [ "$(systemctl is-active ${service})" == "active" ]; then
		echo "⚡️ Stopping $service service..."
		sudo systemctl stop ${service}
	else
		echo "⚡️ $service service is not active."
	fi
}

service_restart() {
	service_check "$@" || return 1
	echo "⚡️ Reloading $service service..."
	sudo systemctl stop ${service}
	sleep 2
	sudo systemctl start ${service}
	wallet_db_exist
}

# View service/daemon logs
service_logs() {
	local lines="${3:-30}"
	service_check ${@}
	echo -e "⚡️ Showing last $lines lines of logs for: ${CYAN}${service}${NC}"
	print_separator
	journalctl -q -u "$service" -n "$lines" --no-pager
	print_separator
}

# View service/daemon status
service_status() {
	service_check ${@}
	echo -e "⚡️ Service status for: ${CYAN}${service}${NC}"
	print_separator
	script -q -c "systemctl status ${service} --no-pager" /dev/null | sed '/^\s*└─/q'
	stty sane # Restore terminal settings
	print_separator
}

config_show() {
	if [ ! -n "$1" ]; then
		echo -e "Usage: $(basename $0) show-config <pkg>\n" && exit 0
	fi
	echo -e "⚡️ Configuration file for: ${CYAN}$1${NC}"
	print_separator
	case "$1" in
		lit)
			if [ ! -f "$LIT_CONF" ]; then
				echo "No config file found. Please run 'sli init lit' to initialize."
			else
				cat ${LIT_CONF}
			fi ;;
		*)
			echo -e "No config file for: ${RED}$1${NC}" ;;
	esac
	print_separator
}

config_edit() {
	if [ ! -n "$1" ]; then
		echo -e "Usage: $(basename $0) edit <pkg>\n" && exit 0
	fi
	case "$1" in
		lit)
			if [ ! -f "$LIT_CONF" ]; then
				echo "No config file, run --> sli init lit"
			else
				${EDITOR} ${LIT_CONF}
			fi ;;
		*)
			echo "No config file for: $1" ;;
	esac
}

#
# --- Wallet Tools and Functions ---
#

# Create a wallet if none
wallet_init() {
	if [ "$1" == "--header" ]; then
		echo "⚡️ Wallet Initialization"
		print_separator
	fi
	if [ ! -f "$LND_DIR/data/chain/bitcoin/mainnet/wallet.db" ]; then
		echo -e "Launching: ${GREEN}lncli create${NC}"
		echo "🔒 Paste your generated or own Wallet password"
		echo ""
		lncli create
	else
		echo "A wallet database already exist:"
		echo -e " --> ${YELLOW}$LND_DIR/data/chain/bitcoin/mainnet/wallet.db${NC}"
	fi
}

wallet_info() {
	if [ "$(lncli state | grep LOCKED)" ]; then
		echo "🔒 Wallet is locked."
	else
		echo "🔒 Wallet is unlocked."
	fi
}

# Used by: service_start and service_restart (litd or lnd)
wallet_db_exist() {
	case "$service" in
		litd|lnd)
			if [ ! -f "$LND_DIR/data/chain/bitcoin/mainnet/wallet.db" ]; then
				echo "🔒 No wallet.db file found."
				return 1
			fi ;;
		cln)
			# If Core lighning is implemented ;-)
			echo "Core lighning" ;;
	esac
}

wallet_new_address() {
	check_command "jq"
	echo "⚡️ New ₿TC Address for onchain funds (p2wkh)"
	print_separator
	addr=$(lncli newaddress p2wkh | jq -r '.address')
	echo "New ₿TC address: $addr"
	log_action "Created BTC onchain address: $addr"
	print_separator
}

wallet_list_addresses() {
	check_command "jq"
	echo "⚡️ Onchain ₿TC Addresses"
	print_separator
	# Exclude addresses without funds ?
	#lncli wallet addresses list | jq -r '.account_with_addresses[].addresses[] | select(.balance != "0") | "\(.address) \(.balance)"'
	lncli wallet addresses list | jq -r '.account_with_addresses[].addresses[] | "\(.address) \(.balance)"'
	print_separator
}

# Let send some sats
wallet_send_onchain() {
	echo "💰 Send ₿TC Onchain (Amount in sat)"
	print_separator && echo ""
	read -p "Address: " addr
	read -p "Amount : " amt
	if [ -n "$addr" ] && [ -n "$amt" ]; then
		lncli sendcoins --addr="$addr" --amount="$amt"
		log_action "Sent $amt sats to $addr"
	fi
}

# Open a channel
wallet_open_channel() {
	echo "🔗 Open a Channel (Amount in sat)"
	print_separator && echo ""
	read -p "Node ID: " node
	read -p "Amount : " amt
	if [ -n "$node" ] && [ -n "$amt" ]; then
		lncli openchannel --node_key="$node" --local_amt="$amt"
		log_action "Opened channel with $node for $amt sats"
	fi
}

# Handle Wallet commands
wallet() {
	case "$2" in
		init) wallet_init "--header" ;;
		new) wallet_new_address ;;
		lsa|lsaddr) wallet_list_addresses ;;
		send) wallet_send_onchain ;;
		opc|openchan) wallet_open_channel ;;
		*) wallet_usage ;;
	esac 
}

#
# --- Packages function: init + install + config files ---
#

# Basic and working lit.conf to get started
lit_config_file() {
	cat << EOT
#
# LiTd Settings: lit.conf
#
uipassword=
lnd-mode=integrated

#
# LND Settings
#

# Wallet
#lnd.wallet-unlock-password-file=${WALLET_PASS}
#lnd.wallet-unlock-allow-create=true

# Set a nice name for your node
lnd.alias=SLiNode

# Optional URL for external fee estimation.
lnd.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json

# Used by Lit UI
lnd.rpcmiddleware.enable=true

#
# Bitcoin Configuration
#

# Use a neutrino light back-end so we don't need a full ₿ node.
lnd.bitcoin.node=neutrino

# Connect to mainnet
lnd.bitcoin.mainnet=1
lnd.bitcoin.active=1

# The seed DNS server(s) to use for initial peer discovery.
lnd.bitcoin.dnsseed=nodes.lightning.directory,soa.nodes.lightning.directory
EOT
}

# Lit Systemd service set to current $USER
lit_service_file() {
	cat << EOT
[Unit]
Description=Lightning Terminal (LIT)
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/litd
User=$USER
Restart=always
RestartSec=60
LimitNOFILE=8192
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOT
	#sudo systemctl enable litd
}

# Lightning Terminal install function
lit_install() {
	
	PKG_NAME="lit"
	SRC_URL="https://github.com/lightninglabs/lightning-terminal/releases/download"
	PKG_VERSION="$(pkg_get_version $PKG_NAME)"
	TARBALL="lightning-terminal-linux-amd64-${PKG_VERSION}.tar.gz"
	SRC_DIR="lightning-terminal-linux-amd64-${PKG_VERSION}"
	DL_URL=${SRC_URL}/${PKG_VERSION}/${TARBALL}

	# Pre install
	pkg_pre_install "lit" "$PKG_VERSION"
	pkg_download_tarball
	pkg_extract_tarball

	# Install to /usr/local/bin
	echo -e "${CYAN}Install path: /usr/local/bin${NC}"
	for bin in $(ls $SRC_DIR); do
		echo " * Installing: $bin"
		sudo cp -f ${SRC_DIR}/${bin} /usr/local/bin
		echo "/usr/local/bin/$bin" >> ${PKG_DATA}/files.list
	done

	# Systemd service
	if [ ! -f /etc/systemd/system/litd.service ]; then
		echo -e "${CYAN}Creating systemd service file:${NC} litd.service"
		lit_service_file > litd.service
		sudo mv litd.service /etc/systemd/system/
		echo "/etc/systemd/system/litd.service" >> ${PKG_DATA}/files.list
		sudo systemctl daemon-reload
	fi
	pkg_post_install
}

# Initialize LiTd
lit_init() {
	echo "⚡️ Lit Initialization"
	print_separator
	if [ ! -f "$LIT_CONF" ]; then
		echo -e "Creating config file: ${YELLOW}$LIT_CONF${NC}"
		mkdir -p ${HOME}/.lit && touch ${LIT_CONF}
		lit_config_file > ${LIT_CONF}
		echo "Setting secure permissions: read only by $USER (0600)"
		chmod 0600 ${LIT_CONF}
	else
		echo -e "Config file already exist:"
		echo -e " --> ${YELLOW}$LIT_CONF${NC}"
	fi
	# Check if uipassword= is empty and offer to creat random password
	ui_password=$(awk -F= '$1=="uipassword"{print $2}' "$LIT_CONF")
	if [ -z "$ui_password" ]; then
		echo ""
		echo -e "${CYAN}Password for Lit Web UI${NC}"
		read -p "Create a secure password ? (yes/no) " gen_uipassword
		if [ "$gen_uipassword" == "yes" ]; then
			password_init ui-password
		fi
	else
		echo " --> uipassword= is set"
	fi
	# We can now start litd and create a Wallet
	echo "" && service_start "start" "litd"
	if [ ! -f "$LND_DIR/data/chain/bitcoin/mainnet/wallet.db" ]; then
		echo ""
		echo -e "${CYAN}Wallet Creation${NC}"
		# Create or use existing wallet password
		if [ ! -f "$WALLET_PASS" ]; then
			read -p "Create a secure password ? (yes/no) " gen_walletpass
			if [ "$gen_walletpass" == "yes" ]; then
				password_init wallet-password
			fi
		else
			echo "Found existing Wallet password:"
			echo -e " --> ${YELLOW}$WALLET_PASS${NC}"
			echo " --> $(cat $WALLET_PASS)"
			echo ""
		fi
		# Now we can initialze wallet
		wallet_init
	else
		echo "🔒 Found Wallet database"
		echo -e " --> ${YELLOW}$WALLET_PASS${NC}"
	fi
	# Wallet auto-unlock
	if [ ! "$(grep ^lnd.wallet-unlock-password-file $LIT_CONF)" ]; then
		echo ""
		echo -e "${CYAN}Wallet Auto-unlock${NC}"
		echo "Let litd auto-unlock the wallet on startup (useful)"
		echo ""
		read -p "Do you wish to enable Wallet auto-unlock ? (yes/no) " auto_unlock
		if [ "$auto_unlock" == "yes" ]; then
			echo "Enabling auto-unlock in: $LIT_CONF"
			sed -i 's/#lnd.wallet-unlock-password-file=/lnd.wallet-unlock-password-file=/' "$LIT_CONF"
			sed -i 's/#lnd.wallet-unlock-allow-create=true/lnd.wallet-unlock-allow-create=true/' "$LIT_CONF"
			echo "Restarting litd to apply auto-unlock..."
			service_restart "restart" "litd"
		else
			echo "Edit lit.conf if you want auto-unlock or run again: sli init"
		fi
	else
		echo "Wallet auto-unlock is enabled"
	fi
}

# lndconnect - https://github.com/LN-Zap/lndconnect
lndconnect_install() {
	
	PKG_NAME="lndconnect"
	SRC_URL="https://github.com/LN-Zap/lndconnect/releases/download/"
	PKG_VERSION="$(pkg_get_version $PKG_NAME)"
	TARBALL="${PKG_NAME}-linux-amd64-${PKG_VERSION}.tar.gz"
	SRC_DIR="${PKG_NAME}-linux-amd64-${PKG_VERSION}"
	DL_URL=${SRC_URL}/${PKG_VERSION}/${TARBALL}
	
	# Pre install
	pkg_pre_install "$PKG_NAME" "$PKG_VERSION"
	pkg_download_tarball
	pkg_extract_tarball
	
	# Install to /usr/local/bin
	echo -e "${CYAN}Install path: /usr/local/bin${NC}"
	echo " * Installing: ${PKG_NAME}"
	sudo cp -f ${SRC_DIR}/${PKG_NAME} /usr/local/bin
	echo "/usr/local/bin/${PKG_NAME}" > ${PKG_DATA}/files.list
	
	# Post install
	pkg_post_install
}

#
# --- Tools functions ---
#

# Convert macaroon to HEX
macaroon_to_hex() {
	local macaroon="${1:-admin}"
	local macaroon="${macaroon%.*}"
	local path="${LND_DIR}/data/chain/bitcoin/mainnet/${macaroon}.macaroon"
	echo -e "⚡️ Convert ${CYAN}$macaroon${NC} macaroon to HEX"
	print_separator
	check_command xxd
	if [ ! -f "${path}" ]; then
		echo "No macaroon found at:"
		echo " --> ${path}"
	else
		xxd -ps -u -c 1000 "${path}"
	fi
	print_separator
}

# Generate strong passwords for Lit UI or Wallet. Prefer pwgen who 
# include special characters
passwords_gen() {
	if [ -x /usr/bin/pwgen ] && [ "$1" != "openssl" ]; then
		wallet_pwd=$(pwgen -c -n -y -s 30 1)
		ui_pwd=$(pwgen -c -n -y -s 30 1)
	else
		wallet_pwd=$(openssl rand -hex 24 | tr -d "=+/")
		ui_pwd=$(openssl rand -hex 24 | tr -d "=+/")
	fi
}

# Change passwords for Lit UI and/or Wallet
passwords_change() {
	echo "⚡️ Change Passwords using: pwgen or openssl"
	print_separator
	echo ""
	passwords_gen ${2}
	echo "Wallet --> ${wallet_pwd}"
	echo "Lit UI --> ${ui_pwd}"
	echo ""
	echo -e "${CYAN}Write down your new password in a secure place!${NC}"
	echo ""
	read -p "Do you wish to change Wallet password ? (yes/no) " change
	if [ "$change" == "yes" ]; then
		echo "You can copy/paste it below."
		lncli changepassword
		# Update a wallet_password file ?
		if [ -f "$WALLET_PASS" ]; then
			echo "Updating: $WALLET_PASS"
			echo "${wallet_pwd}" > "${WALLET_PASS}"
			echo "Setting secure permissions: read only by $USER (0600)"
			chmod 0600 "${WALLET_PASS}"
		fi
	fi
	unset change && echo ""
	if [ -f "$LIT_CONF" ]; then
		read -p "Do you wish to change Lit Web UI password ? (yes/no) " change
		if [ "$change" == "yes" ]; then
			echo "Updating: $LIT_CONF"
			sed -i s/"uipassword=.*"/"uipassword=${ui_pwd}"/ ${LIT_CONF}
			# Lit must reload to use the new password
			service_restart "restart" "litd"
			echo ""
			echo "Make sure your wallet is unlock to login with your new password."
		fi
	fi
	unset wallet_pwd ui_pwd
	echo "" && print_separator
}

# Handle passwords when initializing
password_init() {
	case "$1" in
		ui-password)
			passwords_gen
			echo ""
			echo -e "${YELLOW}Lit UI pass -->${NC} ${ui_pwd}"
			echo ""
			echo "Write down or copy/past your UI password in a secure place."
			read -p "When your password is saved: press ENTER to continue"
			echo ""
			echo -e "${CYAN}Storing Lit UI password in:${NC} $LIT_CONF"
			sed -i s/"uipassword=.*"/"uipassword=${ui_pwd}"/ ${LIT_CONF}
			unset ui_pwd ;;
		wallet-password)
			passwords_gen
			echo ""
			echo -e "${YELLOW}Wallet pass -->${NC} ${wallet_pwd}"
			echo ""
			echo "Write down or copy/past your Wallet password in a secure place."
			read -p "When your password is saved: press ENTER to continue"
			echo ""
			echo -e "${CYAN}Storing Wallet password in:${NC} $WALLET_PASS"
			echo "${wallet_pwd}" > "${WALLET_PASS}"
			echo "Setting secure permissions: read only by $USER (0600)"
			chmod 0600 "${WALLET_PASS}"
			echo "" ;;
	esac
}

#
# --- Packages Manager functions ---
#

pkg_get_version() {
	grep "^${1}|" ${PKGS_LIST} | cut -d "|" -f 2
}

# Download pkg if needed
pkg_download_tarball() {
	if [ ! -f ${CACHE_DIR}/${TARBALL} ]; then
		echo "Downloading: $TARBALL"
		wget -q ${DL_URL} || { echo "Error downloading: ${TARBALL}"; exit 1; }
	else
		echo "Using cache: ${TARBALL}"
	fi
}

pkg_extract_tarball() {
	echo "Extracting: $TARBALL"
	case "$TARBALL" in
		*.tar.gz) tar xzf ${TARBALL} ;;
		*.tar.bz2) tar xjf ${TARBALL} ;;
		*.zip) unzip ${TARBALL} ;;
	esac
}

pkgs_get_list() {
	mkdir -p ${CACHE_DIR} && cd ${CACHE_DIR}
	
	# Get the local packages.list last modification and compare
	local_date=$(stat -c %Y "${SLI_DIR}/packages.list")
	current_date=$(date +%s)
	diff=$((CURRENT_TIME - LOCAL_MOD_TIME))

	# Check if the file is older than 24 hours
	if [ "$diff" -gt 14400 ]; then
		echo "Getting packages list from GitHub..."
		wget -q ${PKGS_URL} || exit 1
		mv -f packages.list ${SLI_DIR}
	else
		echo "The packages list was fetch less than 4h ago."
	fi
}

# Before install: called in pkg install function, ie lit_install
pkg_pre_install() {
	PKG_NAME="$1"
	PKG_VERSION="$2"
	PKG_DATA=${INSTALLED_PKGS}/${PKG_NAME}
	# Already installed ?
	if [ -f "${PKG_DATA}/pkg.conf" ]; then
		# Set version=
		source ${PKG_DATA}/pkg.conf
		# Upgrade or custom version ?
		if [ "$version" == "$PKG_VERSION" ]; then
			echo -e "${CYAN}$PKG_NAME is already installed${NC}"
			echo "Version: $version" && unset version
			echo "" && exit 0
		fi
	fi
	echo "⚡️ Installing: $PKG_NAME $PKG_VERSION"
	print_separator
	# Continuing for install/upgrade - We work in Sli cache directory
	mkdir -p ${PKG_DATA} ${CACHE_DIR} && cd ${CACHE_DIR}
	# Keep track of previous installed files
	mv -f ${PKG_DATA}/files.list ${PKG_DATA}/files.list.old 2>/dev/null
}

# After install
pkg_post_install() {
	# Record version & clean cache
	echo "version=\"$PKG_VERSION\"" > ${PKG_DATA}/pkg.conf
	rm -rf ${SRC_DIR}
	unset PKG_NAME SRC_URL PKG_VERSION TARBALL SRC_DIR DL_URL
}

pkgs_list() {
	echo "⚡️ Installed packages"
	print_separator
	[ -d "$INSTALLED_PKGS" ] || mkdir ${INSTALLED_PKGS}
	for pkg in $(ls ${INSTALLED_PKGS}); do
		source ${INSTALLED_PKGS}/${pkg}/pkg.conf
		echo "$pkg $version" | awk '{ printf "%-15s %-30s\n", $1, $2}'
		unset version
	done
	print_separator
	echo ""
	echo "⚡️ Available packages"
	print_separator
	# Ensure packages.list was downloaded
	[ -f "$PKGS_LIST" ] || pkgs_get_list
	for pkg in $(cat ${PKGS_LIST}); do
		name=$(echo $pkg | cut -d "|" -f 1)
		version=$(echo $pkg | cut -d "|" -f 2)
		echo "$name $version" | awk '{ printf "%-15s %-30s\n", $1, $2}'
	done
	print_separator
}

# Downlad a packages.list, compare installed version to the list
# upgrade everything
pkgs_upgrade() {
	echo "⚡️ Packages Upgrade"
	print_separator
	pkgs_get_list
	echo "Checking for packages update..."
	echo ""
	# Simply check if version differ and upgrade since packages.list is
	# maintained by OxeeLi GitHub repos it sould be fine.
	for pkg in $(ls $INSTALLED_PKGS); do
		source ${INSTALLED_PKGS}/${pkg}/pkg.conf
		available="$(grep "^${pkg}|" ${PKGS_LIST} | cut -d "|" -f 2)"
		if [ "$version" != "$available" ]; then
			echo -e "$pkg ${CYAN}$version${NC} --> ${GREEN}$available${NC}"
			# We want to upgrade SLi at first
			if [ "$pkg" == "sli" ]; then
				upgrades="$pkg $upgrades"
			else
				upgrades="$ugrades $pkg"
			fi
		fi
		unset version available
	done
	nb=$(echo ${upgrades} | wc -w)
	if [ "$nb" -gt "0" ]; then
		echo ""
		read -p "Do you wich to upgrade $nb packages ? (yes/no) " up
		if [ "$up" == "yes" ]; then
			echo ""
			for pkg in ${upgrades}; do
				if [ $(declare -F ${pkg}_install) ]; then
					${pkg}_install
				fi
			done
		fi
	else
		echo -e "${CYAN}Packages are up-to-date.${NC}"
	fi
}

# Remove system files keep config/data in ~/.*
pkg_remove() {
	pkg="$1"
	if [ ! -d ${INSTALLED_PKGS}/${pkg} ]; then
		echo -e "Can't find package: ${RED}$pkg${NC}"
		echo "" && exit 1
	fi
	echo "⚡️ Removing package: $pkg"
	print_separator
	for file in $(cat ${INSTALLED_PKGS}/${pkg}/files.list); do
		echo " * Removing: $file"
		sudo rm -f ${file}
	done
	rm -rf ${INSTALLED_PKGS}/${pkg}
	print_separator
}

#
# --- Handle Command ---
#
handle_command() {
	case "$1" in
	
		init)
			# Initialization
			case "$2" in
				wallet) wallet_init "--header" ;;
				lit) lit_init ;;
				*) sli_init ;;
			esac ;;
	
		start) service_start ${@} ;;
		stop) service_stop ${@} ;;	
		rs|restart) service_restart ${@} ;;
		sc|show-config) config_show ${2} ;;
		ed|edit) config_edit ${2} ;;
		lg|logs) service_logs ${@} ;;
		st|status) service_status ${@} ;;
		
		#
		# --- Tools ---
		#
	
		m2h|macaroon-to-hex) macaroon_to_hex ${2} ;;
		gpw|gen-passwords) passwords_change ${@} ;;
		wa|wallet) wallet ${@} ;;
	
		#
		# --- Packages manager ---
		#
	
		'in'|install)
			if [ "$2" == "sli" ]; then
				echo "If you need to reinstall this version, run: sli init" 
				echo "" && exit 0
			fi
			if [ $(declare -F ${2}_install) ]; then
				${2}_install ${3} # $3 = version
				print_separator
			else
				echo "No package named: $2"
			fi ;;
	
		ls|list)
			pkgs_list ;;
	
		up|upgrade)
			pkgs_upgrade ;;
	
		cc|clean-cache)
			echo "Removing cache directory content..."
			rm -rf ${CACHE_DIR}/* ;;
	
		rm|remove)
			pkg_remove ${2} ;;
	
		*)
			usage ;;
	esac
}

# Let's have default empty line for all actions
echo ""
handle_command ${@}
echo ""
exit 0
